// Mock data for Developer Memory AI
const NOW = new Date('2026-05-15T14:32:00');

const LANGUAGES = {
  TypeScript: '#3178c6',
  JavaScript: '#f1e05a',
  CSS: '#563d7c',
  HTML: '#e34c26',
  Python: '#3572A5',
  Go: '#00ADD8',
  Rust: '#dea584',
  JSON: '#5b8db5',
  Markdown: '#7a7a7a',
};

const PROJECTS = [
  {
    id: 'voyager',
    name: 'voyager-web',
    path: '~/code/voyager-web',
    branch: 'main',
    files: 847,
    loc: 124583,
    contributors: 12,
    lastIndexed: '2 hours ago',
    lastIndexedFull: 'May 15, 2026 · 12:14 PM',
    lastCommit: '14m ago',
    indexing: false,
    summary: "Next.js 14 web client for the Voyager analytics platform. App Router throughout, Server Components by default, with a dedicated 'dashboard' route group that handles auth-gated views. State is split between React Query (server) and Zustand (UI). Charts wrap Recharts; the design system extends Tailwind via shadcn/ui primitives.",
    stack: ['Next.js 14', 'TypeScript', 'TailwindCSS', 'React Query', 'Zustand', 'shadcn/ui', 'Recharts', 'Vitest'],
    langs: [
      { name: 'TypeScript', pct: 78.4 },
      { name: 'CSS', pct: 11.2 },
      { name: 'JavaScript', pct: 6.1 },
      { name: 'JSON', pct: 2.8 },
      { name: 'Markdown', pct: 1.5 },
    ],
  },
  {
    id: 'pulse-api',
    name: 'pulse-api',
    path: '~/code/pulse-api',
    branch: 'develop',
    files: 312,
    loc: 48921,
    contributors: 8,
    lastIndexed: '5 hours ago',
    lastIndexedFull: 'May 15, 2026 · 9:18 AM',
    lastCommit: '2h ago',
    indexing: false,
    summary: 'Go-based REST + gRPC API powering Pulse telemetry ingest. Uses chi router, sqlx over Postgres, NATS for fan-out, and OpenTelemetry for tracing.',
    stack: ['Go 1.22', 'chi', 'sqlx', 'PostgreSQL', 'NATS', 'OpenTelemetry'],
    langs: [
      { name: 'Go', pct: 89.1 },
      { name: 'JSON', pct: 5.2 },
      { name: 'Markdown', pct: 3.4 },
      { name: 'HTML', pct: 2.3 },
    ],
  },
  {
    id: 'atlas-ml',
    name: 'atlas-ml',
    path: '~/code/atlas-ml',
    branch: 'main',
    files: 196,
    loc: 31204,
    contributors: 5,
    lastIndexed: '1 day ago',
    lastIndexedFull: 'May 14, 2026 · 3:42 PM',
    lastCommit: '1d ago',
    indexing: false,
    summary: 'Embedding + retrieval pipeline for the Atlas knowledge base. PyTorch model training scripts, FastAPI serving layer, Qdrant for vector storage.',
    stack: ['Python 3.12', 'PyTorch', 'FastAPI', 'Qdrant', 'pydantic'],
    langs: [
      { name: 'Python', pct: 94.2 },
      { name: 'JSON', pct: 3.1 },
      { name: 'Markdown', pct: 2.7 },
    ],
  },
  {
    id: 'helio-cli',
    name: 'helio-cli',
    path: '~/code/helio-cli',
    branch: 'main',
    files: 64,
    loc: 8412,
    contributors: 3,
    lastIndexed: 'Indexing…',
    lastIndexedFull: '',
    lastCommit: '3d ago',
    indexing: true,
    indexProgress: 0.68,
    summary: '',
    stack: [],
    langs: [{ name: 'Rust', pct: 100 }],
  },
];

const COMMITS = [
  {
    sha: 'a7f4c91',
    author: 'Maya Chen',
    authorInitials: 'MC',
    when: '14 minutes ago',
    message: 'fix(auth): clear refresh token on session timeout',
    aiSummary: 'Plugs a small leak in <code>useAuth</code>: when the refresh call returns 401 the cached token now gets zeroed before the redirect, preventing a stale token from being replayed on the next page load.',
    filesChanged: 3,
  },
  {
    sha: 'e2d8b03',
    author: 'Jin Park',
    authorInitials: 'JP',
    when: '2 hours ago',
    message: 'feat(dashboard): add streaming chart for live metrics',
    aiSummary: 'Adds <code>&lt;LiveMetricChart&gt;</code> that subscribes to the new <code>/api/metrics/stream</code> SSE endpoint. Uses <code>requestIdleCallback</code> to coalesce updates into 60fps frames.',
    filesChanged: 7,
  },
  {
    sha: '9c1ea44',
    author: 'Sam Reyes',
    authorInitials: 'SR',
    when: '4 hours ago',
    message: 'refactor: extract chart axis logic into useChartAxes hook',
    aiSummary: 'Pulls 140 lines of D3 axis math out of three chart components into one shared hook. No behavior change.',
    filesChanged: 5,
  },
  {
    sha: '4b87f10',
    author: 'Maya Chen',
    authorInitials: 'MC',
    when: 'Yesterday, 6:48 PM',
    message: 'chore(deps): bump next 14.2.3 → 14.2.5',
    aiSummary: 'Routine patch bump. Mostly fixes around App Router metadata and a small <code>Image</code> sizing regression — no source changes needed.',
    filesChanged: 2,
  },
  {
    sha: '01b3d2f',
    author: 'Ravi Iyer',
    authorInitials: 'RI',
    when: 'Yesterday, 11:12 AM',
    message: 'feat(auth): magic-link sign-in for the web client',
    aiSummary: 'Adds a magic-link flow paralleling the existing password sign-in. New <code>POST /auth/magic-link</code> endpoint, a 6-digit code step, and a new <code>MagicLinkForm</code> component composed from the existing <code>AuthCard</code> shell.',
    filesChanged: 14,
  },
];

const TOPICS = [
  'authentication', 'rate limiting', 'charts', 'real-time', 'forms', 'caching', 'routing', 'error handling',
];

window.__MOCK = { NOW, LANGUAGES, PROJECTS, COMMITS, TOPICS };
